#!/bin/sh

# Copy various config bits into src.git to set it up.

DEST="$1"

if test -z "$DEST"; then
    echo "Usage: finalize-new-git-repo PATH-TO-REPO" 1>&2
    exit 1
fi


where=$(dirname $0)

set -x

cp $where/src-git-config $DEST/config
cp $where/src-git-description $DEST/description
cp $where/src-email $DEST/src-email
cp $where/post-receive $DEST/hooks/post-receive
cp $where/update $DEST/hooks/update

mv $DEST/hooks/post-update.sample $DEST/hooks/post-update
